# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITuwxER1YjCWSeXOg7_i8w9TCdnbTWFo
"""

# ============================================
# RESTAURANT RATINGS ANALYSIS
# DATA CLEANING
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
restaurants = pd.read_csv("restaurants.csv")
restaurant_cuisines = pd.read_csv("restaurant_cuisines.csv")
ratings = pd.read_csv("ratings.csv")
consumers = pd.read_csv("consumers.csv")
consumer_preferences = pd.read_csv("consumer_preferences.csv")

# Display shapes
print("Restaurants:", restaurants.shape)
print("Restaurant Cuisines:", restaurant_cuisines.shape)
print("Ratings:", ratings.shape)
print("Consumers:", consumers.shape)
print("Consumer Preferences:", consumer_preferences.shape)

datasets = {
    "Restaurants": restaurants,
    "Restaurant Cuisines": restaurant_cuisines,
    "Ratings": ratings,
    "Consumers": consumers,
    "Consumer Preferences": consumer_preferences
}

for name, df in datasets.items():
    print("\n", "="*50)
    print(name)
    print("="*50)
    print(df.isnull().sum())

restaurants = restaurants.drop_duplicates()
restaurant_cuisines = restaurant_cuisines.drop_duplicates()
ratings = ratings.drop_duplicates()
consumers = consumers.drop_duplicates()
consumer_preferences = consumer_preferences.drop_duplicates()

print("Duplicates removed successfully.")

# Restaurants
restaurants["Alcohol_Service"] = restaurants["Alcohol_Service"].fillna("Not Available")
restaurants["Parking"] = restaurants["Parking"].fillna("Not Available")

# Consumers
consumer_columns = [
    "Smoker",
    "Transportation_Method",
    "Marital_Status",
    "Children",
    "Occupation",
    "Budget"
]

for col in consumer_columns:
    consumers[col] = consumers[col].fillna("Unknown")

print(restaurants.dtypes)
print(ratings.dtypes)
print(consumers.dtypes)

restaurants["Restaurant_ID"] = restaurants["Restaurant_ID"].astype(str)

restaurant_cuisines["Restaurant_ID"] = \
    restaurant_cuisines["Restaurant_ID"].astype(str)

ratings["Restaurant_ID"] = ratings["Restaurant_ID"].astype(str)
ratings["Consumer_ID"] = ratings["Consumer_ID"].astype(str)

consumers["Consumer_ID"] = consumers["Consumer_ID"].astype(str)

consumer_preferences["Consumer_ID"] = \
    consumer_preferences["Consumer_ID"].astype(str)

# Merge ratings with restaurant information

master = ratings.merge(
    restaurants,
    on="Restaurant_ID",
    how="left"
)

# Add cuisine information
master = master.merge(
    restaurant_cuisines,
    on="Restaurant_ID",
    how="left"
)

# Add consumer information
master = master.merge(
    consumers,
    on="Consumer_ID",
    how="left",
    suffixes=("_restaurant", "_consumer")
)

# Add consumer preference
master = master.merge(
    consumer_preferences,
    on="Consumer_ID",
    how="left"
)

print(master.shape)
print(master.head())

master.to_csv(
    "restaurant_ratings_master_cleaned.csv",
    index=False
)

print("Cleaned master dataset saved.")

print(master.describe())

print(master["Overall_Rating"].value_counts().sort_index())

print("Average Overall Rating:",
      master["Overall_Rating"].mean())

print("Average Food Rating:",
      master["Food_Rating"].mean())

print("Average Service Rating:",
      master["Service_Rating"].mean())

plt.figure(figsize=(8,5))

sns.countplot(
    data=master,
    x="Overall_Rating"
)

plt.title("Distribution of Overall Restaurant Ratings")
plt.xlabel("Overall Rating")
plt.ylabel("Number of Ratings")

plt.show()

rating_comparison = master[
    ["Overall_Rating", "Food_Rating", "Service_Rating"]
].mean()

print(rating_comparison)

rating_comparison.plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Average Restaurant Rating Comparison")
plt.xlabel("Rating Type")
plt.ylabel("Average Rating")

plt.show()

restaurant_summary = master.groupby(
    ["Restaurant_ID", "Name"]
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Food_Rating=("Food_Rating", "mean"),
    Service_Rating=("Service_Rating", "mean"),
    Rating_Count=("Overall_Rating", "count")
).reset_index()

top_restaurants = restaurant_summary[
    restaurant_summary["Rating_Count"] >= 5
].sort_values(
    by="Average_Rating",
    ascending=False
)

print(top_restaurants.head(10))

top10 = top_restaurants.head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    data=top10,
    y="Name",
    x="Average_Rating"
)

plt.title("Top 10 Rated Restaurants")
plt.xlabel("Average Rating")
plt.ylabel("Restaurant")

plt.show()

cuisine_analysis = master.groupby(
    "Cuisine"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Food_Rating=("Food_Rating", "mean"),
    Service_Rating=("Service_Rating", "mean"),
    Number_of_Ratings=("Overall_Rating", "count")
).reset_index()

cuisine_analysis = cuisine_analysis.sort_values(
    "Average_Rating",
    ascending=False
)

print(cuisine_analysis)

popular_cuisines = master["Cuisine"].value_counts()

print(popular_cuisines.head(10))

top_cuisines = cuisine_analysis.head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    data=top_cuisines,
    y="Cuisine",
    x="Average_Rating"
)

plt.title("Top Rated Cuisines")
plt.xlabel("Average Rating")
plt.ylabel("Cuisine")

plt.show()

preference_count = consumer_preferences[
    "Preferred_Cuisine"
].value_counts()

print(preference_count.head(15))

plt.figure(figsize=(10,6))

preference_count.head(10).plot(
    kind="bar"
)

plt.title("Top Consumer Cuisine Preferences")
plt.xlabel("Cuisine")
plt.ylabel("Number of Consumers")

plt.xticks(rotation=45)

plt.show()

preference_rating = master.groupby(
    "Preferred_Cuisine"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Number_of_Ratings=("Overall_Rating", "count")
).reset_index()

preference_rating = preference_rating.sort_values(
    "Average_Rating",
    ascending=False
)

print(preference_rating)

budget_analysis = master.groupby(
    "Budget"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Number_of_Ratings=("Overall_Rating", "count")
).reset_index()

print(budget_analysis)

budget_analysis = master.groupby(
    "Budget"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Number_of_Ratings=("Overall_Rating", "count")
).reset_index()

print(budget_analysis)

sns.barplot(
    data=budget_analysis,
    x="Budget",
    y="Average_Rating"
)

plt.title("Average Restaurant Rating by Consumer Budget")
plt.show()

age_analysis = master.groupby(
    "Age"
)["Overall_Rating"].mean()

plt.figure(figsize=(10,5))

plt.plot(
    age_analysis.index,
    age_analysis.values,
    marker="o"
)

plt.title("Average Restaurant Rating by Age")
plt.xlabel("Age")
plt.ylabel("Average Rating")

plt.show()

occupation_analysis = master.groupby(
    "Occupation"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Rating_Count=("Overall_Rating", "count")
).reset_index()

print(occupation_analysis)

city_analysis = master.groupby(
    "City_restaurant"
).agg(
    Average_Rating=("Overall_Rating", "mean"),
    Rating_Count=("Overall_Rating", "count")
).reset_index()

print(city_analysis)

print(master.columns.tolist())

numeric_columns = [
    "Overall_Rating",
    "Food_Rating",
    "Service_Rating",
    "Age"
]

correlation = master[numeric_columns].corr()

print(correlation)

plt.figure(figsize=(8,6))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Between Numerical Variables")

plt.show()

ml_data = master[
    [
        "Food_Rating",
        "Service_Rating",
        "Age",
        "Budget",
        "Occupation",
        "Price",
        "Franchise",
        "Alcohol_Service",
        "Cuisine",
        "Overall_Rating"
    ]
].copy()

ml_data = ml_data.dropna(
    subset=["Overall_Rating"]
)

X = ml_data.drop(
    "Overall_Rating",
    axis=1
)

y = ml_data["Overall_Rating"]

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

categorical_columns = [
    "Budget",
    "Occupation",
    "Price",
    "Franchise",
    "Alcohol_Service",
    "Cuisine"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_columns
        )
    ],
    remainder="passthrough"
)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "regressor",
            RandomForestRegressor(
                n_estimators=200,
                random_state=42
            )
        )
    ]
)

model.fit(
    X_train,
    y_train
)

y_pred = model.predict(X_test)

mae = mean_absolute_error(
    y_test,
    y_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

r2 = r2_score(
    y_test,
    y_pred
)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

results = pd.DataFrame({
    "Actual_Rating": y_test.values,
    "Predicted_Rating": y_pred
})

print(results.head(20))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

classifier = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            RandomForestClassifier(
                n_estimators=200,
                random_state=42
            )
        )
    ]
)

classifier.fit(
    X_train,
    y_train
)

prediction = classifier.predict(X_test)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        prediction
    )
)

print(
    classification_report(
        y_test,
        prediction
    )
)

import joblib

joblib.dump(
    model,
    "restaurant_rating_prediction_model.pkl"
)

print("Model saved successfully.")